default_inputdir: .
ida:
  idat32: C:/Program Files/IDA Professional 9.0/idat.exe
  idat64: C:/Program Files/IDA Professional 9.0/idat.exe
<<<<<<< HEAD
log_level: INFO
=======
>>>>>>> 0543c92 (Доработка для анализа MacOS/iOS)
max_ida: 6
theme: light
